name: Build and deploy Node.js app to Azure Web App - dynamic-portfolio

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install npm dependencies
        run: npm install

      - name: npm run build and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Remove node_modules before uploading
        run: rm -rf node_modules
        if: ${{ success() }}  # Only run if tests and build were successful

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Restore npm dependencies
        run: npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dynamic-portfolio'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F441C110875D47D9BF14BA3FB7E4D97A }}
          package: .

  merge_on_build_pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: npm run build and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Merge into master
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config user.name "muhammad-aftab93"
          git config user.email "muhammad.aftab93@yahoo.com"
          git checkout master
          git merge $GITHUB_SHA
          git push origin master
          