name: Merge on Build Pass

on:
  push:
    branches:
      - master  # The branch where the pull request will be merged

jobs:
  
  merge_on_build_pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: npm run build and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Merge into master
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config user.name "muhammad-aftab93"
          git config user.email "muhammad.aftab93@yahoo.com"
          git checkout master
          git merge $GITHUB_SHA
          git push origin master
